{{- if and .Values.manager.enabled (not .Values.manager.llm.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upstatus.manager.fullname" . }}-llm
  labels:
    {{- include "upstatus.manager.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.manager.llm.apiKey | b64enc | quote }}
{{- end }}
