{{- if and .Values.manager.enabled .Values.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "upstatus.manager.serviceAccountName" . }}
  labels:
    {{- include "upstatus.manager.labels" . | nindent 4 }}
  {{- with .Values.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
