{{- if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "upstatus.manager.fullname" . }}
  labels:
    {{- include "upstatus.manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "upstatus.manager.selectorLabels" . | nindent 4 }}
{{- end }}
