{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "upstatus.agent.fullname" . }}
  labels:
    {{- include "upstatus.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "upstatus.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "upstatus.agent.selectorLabels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "upstatus.agent.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}-agent
        image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        args:
        - "-v={{ .Values.agent.agent.verbosity }}" # Set verbosity level from values
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_ROTATION_WINDOW
          value: "{{ .Values.agent.agent.logRotationWindow }}"
        - name: MAX_MEMORY_USAGE_MB
          value: "{{ .Values.agent.agent.maxMemoryUsageMB }}"
        - name: BUFFER_SIZE_BYTES
          value: "{{ .Values.agent.agent.bufferSizeBytes }}"
        - name: NAMESPACE_FILTER_MODE
          value: "{{ .Values.agent.agent.namespaces.mode }}"
        - name: NAMESPACE_FILTER_LIST
          value: "{{ .Values.agent.agent.namespaces.list }}"
        - name: NAMESPACE_BLACKLIST_SYSTEM
          value: "{{ .Values.agent.agent.namespaces.blacklistSystem }}"
        - name: INCLUDE_LABELS
          value: "{{ .Values.agent.agent.labels.include }}"
        - name: EXCLUDE_LABELS
          value: "{{ .Values.agent.agent.labels.exclude }}"
        - name: METRICS_ENABLED
          value: "{{ .Values.agent.agent.metricsEnabled }}"
        - name: METRICS_PORT
          value: "{{ .Values.agent.agent.metricsPort }}"
        - name: HEALTH_CHECK_PORT
          value: "{{ .Values.agent.agent.healthCheckPort }}"
        ports:
        - containerPort: {{ .Values.agent.agent.metricsPort }}
          name: metrics
        - containerPort: {{ .Values.agent.agent.healthCheckPort }}
          name: health
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.agent.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.agent.securityContext | nindent 10 }}
          # Ensure we can read log files
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        # Mount container logs directory
        - name: varlog
          mountPath: /var/log
          readOnly: true
        # For position tracking
        - name: upstatus-state
          mountPath: /var/upstatus/state
        # For registry file position tracking
        - name: upstatus-registry
          mountPath: /var/lib/upstatus-agent/registry
      volumes:
      # Container logs and symlinks
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      # State directory for position tracking
      - name: upstatus-state
        hostPath:
          path: /var/upstatus/state
          type: DirectoryOrCreate
      # Registry directory for file position tracking
      - name: upstatus-registry
        hostPath:
          path: /var/lib/upstatus-agent/registry
          type: DirectoryOrCreate
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
